#!/usr/bin/bash

# Time the script was started
export STARTTIME=$(date)

# All toci working files should go here
export TOCI_WORKING_DIR=${TOCI_WORKING_DIR:-/opt/toci}
export TRIPLEO_ROOT=$TOCI_WORKING_DIR # some scripts are expecting this

# Should toci get tripleo repositories
export TOCI_GIT_CHECKOUT=${TOCI_GIT_CHECKOUT:-1}

# Files that should be cached between runs should go in here
# e.g. downloaded images, git repo's etc...
export TOCI_CACHE_DIR=${TOCI_CACHE_DIR:-/var/tmp/toci_cache}

# Any files to be uploaded to results server go here
export TOCI_LOG_DIR=${TOCI_LOG_DIR:-$(mktemp -d --tmpdir toci_logs_XXXXXXX)}

# Set TOCI_ARCH to x86_64 to build 64 bit arch
export TOCI_ARCH=${TOCI_ARCH:-'i386'}
export TOCI_DIB_ARCH='i386'
if [ "$TOCI_ARCH" == 'x86_64' ]; then
  export TOCI_DIB_ARCH='amd64'
fi

# This gets passed into diskimage builder
export NODE_DIST=${NODE_DIST:-'pip-cache fedora selinux-permissive'}

export DHCP_DRIVER=${DHCP_DRIVER:-'bm-dnsmasq'}

# Set to 0 if you don't want an overcloud to be started
export TOCI_DO_OVERCLOUD=${TOCI_DO_OVERCLOUD:-1}

# This is needed for help build the index.html if upload results to server
export RESULT_CACHE=${RESULT_CACHE:-$TOCI_CACHE_DIR/results_cache.html}

# Add incubator scripts to path
export PATH=$PATH:$TOCI_WORKING_DIR/tripleo-incubator/scripts

# Should toci remove VM's when finished
export TOCI_CLEANUP=${TOCI_CLEANUP:-0}

# Should toci remove WORKING and LOG dirs when finished
export TOCI_REMOVE=${TOCI_REMOVE:-0}

# Should toci upload results to a server
export TOCI_UPLOAD=${TOCI_UPLOAD:-0}

# irc channel (on freenode) to notify on error
export TOCI_IRC

# bm_poser host resources, use by various scripts
export TOCI_NODE_CPU=${TOCI_NODE_CPU:-1}     # Number of cpu's
export TOCI_NODE_MEM=${TOCI_NODE_MEM:-2048}  # RAM MB
export TOCI_NODE_DISK=${TOCI_NODE_DISK:-30}  # Disk size

export TOCI_ADMIN_TOKEN='admin'
export UNDERCLOUD_ADMIN_PASSWORD='stack'
export OVERCLOUD_ADMIN_PASSWORD='stack'
export OVERCLOUD_DEMO_PASSWORD='stack'

# don't care what we use here, since we shouldn't be using this feature in undercloud-live
export TOCI_REPOREF_bm_poseur=13c6574
# havana rc1
export TOCI_REPOREF_cinder=f021629
# same as above, which matches v0.1.2
export TOCI_REPOREF_config_applier=5a0470f
# don't care what we use here, since we shouldn't be using this feature in undercloud-live
export TOCI_REPOREF_devstack=b48e008
# v0.0.4
export TOCI_REPOREF_diskimage_builder=9211a7fecbadc13e8254085133df1e3b53f150d8
# havana rc1
export TOCI_REPOREF_glance=04cd202
# havana rc1
export TOCI_REPOREF_heat=605eb36
# don't care what we use here, since we shouldn't be using this feature in undercloud-live
# note: this is not tripleo-incubator which is set below
export TOCI_REPOREF_incubator=5c72571
# havana rc1
export TOCI_REPOREF_keystone=b6b1e30
# havana rc1
export TOCI_REPOREF_neutron=d90649f
# havana rc1
export TOCI_REPOREF_nova=96d828f
# don't care what we use here, since we shouldn't be using this feature in undercloud-live
export TOCI_REPOREF_novnc=3cb89f5
# v0.1.2
export TOCI_REPOREF_os_collect_config=ff45223
# same as above, which matches v0.0.2
export TOCI_REPOREF_os_refresh_config=8386314
# v0.10.0
export TOCI_REPOREF_python_glanceclient=eb47b55
# v0.2.4
export TOCI_REPOREF_python_heatclient=2c05c73
# v0.3.2
export TOCI_REPOREF_python_keystoneclient=6441f2b
# v2.3.0
export TOCI_REPOREF_python_neutronclient=b1f348a
# v2.15.0
export TOCI_REPOREF_python_novaclient=45fcd6f
# from https://github.com/agroup/undercloud-live/blob/master/bin/install.sh#58
export TOCI_REPOREF_tripleo_heat_templates=0dbf2810a0ee78658c35e61dc447c5f968226cb9
# from 2013-09-30  (just after v0.0.2)
export TOCI_REPOREF_tripleo_image_elements=6e4ae3944bece239e25d7c8f8fe3494f145961d0
# from https://github.com/agroup/undercloud-live/blob/master/bin/install.sh#L40
export TOCI_REPOREF_tripleo_incubator=8031466

#export CUSTOM_RELEASE=1
#export DIB_OFFLINE=1
#export EXTRA_ELEMENTS="local-pypi"
