#!/usr/bin/bash

# Time the script was started
export STARTTIME=$(date)

# All toci working files should go here
export TOCI_WORKING_DIR=${TOCI_WORKING_DIR:-/opt/toci}
export TRIPLEO_ROOT=$TOCI_WORKING_DIR # some scripts are expecting this

# Should toci get tripleo repositories
export TOCI_GIT_CHECKOUT=${TOCI_GIT_CHECKOUT:-1}

# Files that should be cached between runs should go in here
# e.g. downloaded images, git repo's etc...
export TOCI_CACHE_DIR=${TOCI_CACHE_DIR:-/var/tmp/toci_cache}

# Any files to be uploaded to results server go here
export TOCI_LOG_DIR=${TOCI_LOG_DIR:-$(mktemp -d --tmpdir toci_logs_XXXXXXX)}

# Set TOCI_ARCH to x86_64 to build 64 bit arch
export TOCI_ARCH=${TOCI_ARCH:-'i386'}
export TOCI_DIB_ARCH='i386'
if [ "$TOCI_ARCH" == 'x86_64' ]; then
  export TOCI_DIB_ARCH='amd64'
fi

# This gets passed into diskimage builder
export NODE_DIST=${NODE_DIST:-'pip-cache fedora selinux-permissive'}

export DHCP_DRIVER=${DHCP_DRIVER:-'bm-dnsmasq'}

# Set to 0 if you don't want an overcloud to be started
export TOCI_DO_OVERCLOUD=${TOCI_DO_OVERCLOUD:-1}

# This is needed for help build the index.html if upload results to server
export RESULT_CACHE=${RESULT_CACHE:-$TOCI_CACHE_DIR/results_cache.html}

# Add incubator scripts to path
export PATH=$PATH:$TOCI_WORKING_DIR/tripleo-incubator/scripts

# Should toci remove VM's when finished
export TOCI_CLEANUP=${TOCI_CLEANUP:-0}

# Should toci remove WORKING and LOG dirs when finished
export TOCI_REMOVE=${TOCI_REMOVE:-0}

# Should toci upload results to a server
export TOCI_UPLOAD=${TOCI_UPLOAD:-0}

# irc channel (on freenode) to notify on error
export TOCI_IRC

# bm_poser host resources, use by various scripts
export TOCI_NODE_CPU=${TOCI_NODE_CPU:-1}     # Number of cpu's
export TOCI_NODE_MEM=${TOCI_NODE_MEM:-2048}  # RAM MB
export TOCI_NODE_DISK=${TOCI_NODE_DISK:-30}  # Disk size

export TOCI_ADMIN_TOKEN='admin'
export UNDERCLOUD_ADMIN_PASSWORD='stack'
export OVERCLOUD_ADMIN_PASSWORD='stack'
export OVERCLOUD_DEMO_PASSWORD='stack'

export TOCI_REPOREF_bm_poseur=13c6574
export TOCI_REPOREF_cinder=e01eba47b94c3cbb41491acdbcabd9ba14936be6
export TOCI_REPOREF_config_applier=5a0470f
export TOCI_REPOREF_devstack=b48e008
export TOCI_REPOREF_diskimage_builder=d5afe2b
export TOCI_REPOREF_glance=f4f2a82
export TOCI_REPOREF_heat=002dcaa
export TOCI_REPOREF_incubator=5c72571
export TOCI_REPOREF_keystone=ec4680a
export TOCI_REPOREF_neutron=6d089df
export TOCI_REPOREF_nova=a6bc12c
export TOCI_REPOREF_novnc=3cb89f5
export TOCI_REPOREF_os_collect_config=f1f71c0
export TOCI_REPOREF_os_refresh_config=8386314
export TOCI_REPOREF_python_glanceclient=7a4a8a0
export TOCI_REPOREF_python_heatclient=96dbb09
export TOCI_REPOREF_python_keystoneclient=baa9490
export TOCI_REPOREF_python_neutronclient=16bf282
export TOCI_REPOREF_python_novaclient=2ab3344
export TOCI_REPOREF_tripleo_heat_templates=69f1dcc
export TOCI_REPOREF_tripleo_image_elements=941ac61
export TOCI_REPOREF_tripleo_incubator=fd9d825
export CUSTOM_RELEASE=1
export DIB_OFFLINE=1
export EXTRA_ELEMENTS="local-pypi"
